// Every world gets a generated "worldsmith" data pack. Its load function re-applies the world's
// game rules on every boot and /reload, so settings can't drift. The builder (Phase 2) adds its
// functions, structures and loot tables to the same pack.

import { checkGamerule, datapackMeta, loadVersion } from "@worldsmith/mcdata";
import type { WorldFile, WorldSpec } from "./world.ts";

/** itzg's default level name; data packs live in <level>/datapacks. */
export const LEVEL_NAME = "world";
export const DATAPACK_DIR = `${LEVEL_NAME}/datapacks/worldsmith`;

export class SpecError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SpecError";
  }
}

/** Game rules as the world's version spells them (legacy names translated, unknown ones rejected). */
export function resolveGamerules(spec: WorldSpec): Record<string, boolean | number> {
  const data = loadVersion(spec.minecraft.version);
  const wanted: Record<string, boolean | number> = { ...spec.gamerules };
  // In 26.x PvP moved from server.properties to a game rule.
  if (spec.properties.pvp !== undefined && data?.gamerules.pvp) wanted.pvp = spec.properties.pvp;
  if (spec.properties.enableCommandBlock && data?.gamerules.command_blocks_work) wanted.command_blocks_work = true;
  if (!data) return wanted; // no reference for this version: pass through, the server will validate
  const out: Record<string, boolean | number> = {};
  for (const [raw, value] of Object.entries(wanted)) {
    const r = checkGamerule(data, raw);
    if (!r.ok) throw new SpecError(`${r.error}${r.suggestions.length ? ` Did you mean ${r.suggestions.join(", ")}?` : ""}`);
    if ((r.type === "bool") !== (typeof value === "boolean")) {
      throw new SpecError(`Game rule ${r.name} takes ${r.type === "bool" ? "true/false" : "a whole number"}, not ${JSON.stringify(value)}.`);
    }
    out[r.name] = r.note === "inverted" && typeof value === "boolean" ? !value : value;
  }
  return out;
}

export function worldDatapack(spec: WorldSpec): WorldFile[] {
  const data = loadVersion(spec.minecraft.version);
  const gamerules = resolveGamerules(spec);
  const load = [
    "# Generated by WorldSmith. Re-applied on every start and /reload.",
    ...Object.entries(gamerules).map(([k, v]) => `gamerule ${k} ${v}`),
    "",
  ].join("\n");
  const meta = data
    ? datapackMeta(data, `WorldSmith settings for ${spec.name}`)
    : JSON.stringify({ pack: { description: `WorldSmith settings for ${spec.name}` } });
  return [
    { kind: "inline", encoding: "utf8", path: `${DATAPACK_DIR}/pack.mcmeta`, content: meta },
    { kind: "inline", encoding: "utf8", path: `${DATAPACK_DIR}/data/minecraft/tags/function/load.json`, content: JSON.stringify({ values: ["worldsmith:load"] }) },
    { kind: "inline", encoding: "utf8", path: `${DATAPACK_DIR}/data/worldsmith/function/load.mcfunction`, content: load },
  ];
}
