// WorldSpec: everything needed to create one world, fully pinned. Plans (Phase 2) and recipes
// both produce a WorldSpec; the worker turns it into an itzg/minecraft-server container.

import { z } from "zod";

export const ServerType = z.enum(["VANILLA", "PAPER", "FABRIC", "NEOFORGE"]);
export type ServerType = z.infer<typeof ServerType>;

const Slug = z.string().regex(/^[a-z0-9][a-z0-9-]{1,30}$/, "lowercase letters, digits and dashes");

/** A path inside the world's /data volume. Relative, no traversal, no absolute paths. */
export const DataPath = z
  .string()
  .min(1)
  .max(200)
  .refine((p) => !p.startsWith("/") && !p.includes("\\") && !p.split("/").some((seg) => seg === ".." || seg === ""), {
    message: "must be a relative path inside the world (no '..', no leading '/')",
  });

/** A file placed into the world before it starts: plugins, add-ons, datapacks, configs. */
export const WorldFile = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("download"),
    /** Where it came from, for the plan card and audits. */
    source: z.enum(["modrinth", "hangar", "curseforge", "geysermc", "url"]),
    project: z.string().optional(),
    version: z.string().optional(),
    url: z.url({ protocol: /^https$/ }),
    /** Every download is hash-checked before it reaches the world. */
    sha512: z.string().regex(/^[0-9a-f]{128}$/),
    path: DataPath,
  }),
  z.object({
    kind: z.literal("inline"),
    /** Generated by WorldSmith/Claude (datapack files, plugin configs). UTF-8 text or base64. */
    content: z.string().max(5_000_000),
    encoding: z.enum(["utf8", "base64"]).default("utf8"),
    path: DataPath,
    /** Seed files: write only if the world doesn't have this file yet (never clobber later edits). */
    onlyIfMissing: z.boolean().optional(),
  }),
]);
export type WorldFile = z.infer<typeof WorldFile>;

export const WorldProperties = z
  .object({
    motd: z.string().max(120),
    difficulty: z.enum(["peaceful", "easy", "normal", "hard"]),
    gamemode: z.enum(["survival", "creative", "adventure", "spectator"]),
    pvp: z.boolean(),
    hardcore: z.boolean(),
    viewDistance: z.number().int().min(3).max(32),
    simulationDistance: z.number().int().min(3).max(32),
    spawnProtection: z.number().int().min(0).max(64),
    levelType: z.enum(["normal", "flat", "large_biomes", "amplified", "single_biome_surface"]),
    seed: z.string().max(64),
    allowFlight: z.boolean(),
    enableCommandBlock: z.boolean(),
  })
  .partial();
export type WorldProperties = z.infer<typeof WorldProperties>;

export const WorldSpec = z.object({
  slug: Slug,
  name: z.string().min(1).max(60),
  /** Recipe this world was created from, if any. */
  recipe: z.string().optional(),
  minecraft: z.object({
    version: z.string().regex(/^\d+(\.\d+){1,2}$/),
    /** Network protocol of that version; the gatekeeper uses it for version help. */
    protocol: z.number().int().positive(),
    type: ServerType,
  }),
  memoryMb: z.number().int().min(1024).max(12288),
  files: z.array(WorldFile).default([]),
  properties: WorldProperties.default({}),
  gamerules: z.record(z.string().regex(/^[a-zA-Z_]+$/), z.union([z.boolean(), z.number().int()])).default({}),
  crossplay: z.object({ bedrock: z.boolean() }).default({ bedrock: false }),
  /** Minutes with nobody online before the world goes to sleep. */
  idleSleepMinutes: z.number().int().min(1).max(1440).default(10),
});
export type WorldSpec = z.infer<typeof WorldSpec>;

export interface CompiledWorld {
  image: string;
  env: Record<string, string>;
  /** Hard container memory cap: JVM heap + overhead. */
  memoryLimitBytes: number;
}

const JVM_OVERHEAD_MB = 1280; // measured: Paper + BentoBox sits ~0.45 GiB above a 3 GiB heap; leave room for spikes

/**
 * WorldSpec → itzg/minecraft-server container settings. Security settings are not optional:
 * online-mode, whitelist and enforce-whitelist are always on, and RCON is always enabled with
 * a per-world secret (reachable only on the internal worlds network).
 */
export function compileWorld(spec: WorldSpec, opts: { rconPassword: string }): CompiledWorld {
  if (opts.rconPassword.length < 24) throw new Error("RCON password must be at least 24 characters");
  const p = spec.properties;
  const env: Record<string, string> = {
    EULA: "TRUE",
    TYPE: spec.minecraft.type,
    VERSION: spec.minecraft.version,
    MEMORY: `${spec.memoryMb}M`,
    ONLINE_MODE: "TRUE",
    ENABLE_WHITELIST: "TRUE",
    ENFORCE_WHITELIST: "TRUE",
    ENABLE_RCON: "TRUE",
    RCON_PASSWORD: opts.rconPassword,
    OVERRIDE_SERVER_PROPERTIES: "TRUE",
    // Paper and vanilla 1.20.5+: hide the player sample from server-list scanners.
    HIDE_ONLINE_PLAYERS: "TRUE",
    MOTD: p.motd ?? spec.name,
    SNOOPER_ENABLED: "FALSE",
  };
  const map: [keyof WorldProperties, string, (v: never) => string][] = [
    ["difficulty", "DIFFICULTY", String],
    ["gamemode", "MODE", String],
    ["pvp", "PVP", (v: boolean) => String(v).toUpperCase()],
    ["hardcore", "HARDCORE", (v: boolean) => String(v).toUpperCase()],
    ["viewDistance", "VIEW_DISTANCE", String],
    ["simulationDistance", "SIMULATION_DISTANCE", String],
    ["spawnProtection", "SPAWN_PROTECTION", String],
    ["levelType", "LEVEL_TYPE", String],
    ["seed", "SEED", String],
    ["allowFlight", "ALLOW_FLIGHT", (v: boolean) => String(v).toUpperCase()],
    ["enableCommandBlock", "ENABLE_COMMAND_BLOCK", (v: boolean) => String(v).toUpperCase()],
  ];
  for (const [key, envName, fmt] of map) {
    const v = p[key];
    if (v !== undefined) env[envName] = fmt(v as never);
  }
  if (spec.crossplay.bedrock) {
    // Floodgate (Bedrock) players can't sign chat messages; Java servers must not require it.
    env.ENFORCE_SECURE_PROFILE = "FALSE";
  }
  if (spec.minecraft.type === "PAPER") env.PATCH_DEFINITIONS = `/data/${PATCH_DIR}`;
  return {
    image: "itzg/minecraft-server:java25",
    env,
    memoryLimitBytes: (spec.memoryMb + JVM_OVERHEAD_MB) * 1024 * 1024,
  };
}

/** itzg applies JSON-path patch sets from this directory at every start. */
export const PATCH_DIR = "worldsmith/patches";

/**
 * Server config WorldSmith needs regardless of recipe. Every player arrives through the gatekeeper,
 * so the world sees one source IP for everyone: Paper's per-IP login throttle (4 s) would refuse
 * friends who join together. The gatekeeper is the front door now, so the throttle is turned off.
 */
export function serverConfigFiles(spec: WorldSpec): WorldFile[] {
  if (spec.minecraft.type !== "PAPER") return [];
  // One patch definition per file in the directory (not the {"patches":[…]} set format).
  const patches = {
    file: "/data/bukkit.yml",
    ops: [{ $set: { path: "$.settings['connection-throttle']", value: 0, "value-type": "int" } }],
  };
  return [
    { kind: "inline", encoding: "utf8", onlyIfMissing: false, path: `${PATCH_DIR}/bukkit.json`, content: JSON.stringify(patches, null, 2) },
    // Patches can't apply before bukkit.yml exists (first boot); seed it. Paper fills in every other default.
    { kind: "inline", encoding: "utf8", onlyIfMissing: true, path: "bukkit.yml", content: "settings:\n  connection-throttle: 0\n" },
  ];
}

/** Docker names derived from the slug, shared by worker and gatekeeper. */
export function worldContainerName(slug: string): string {
  return `ws-world-${slug}`;
}
export function worldVolumeName(slug: string): string {
  return `ws-world-${slug}-data`;
}
